#spring.application.name=content-hub

spring:
  application:
    name: content-hub
  jackson:
    #property-naming-strategy: SNAKE_CASE
    property-naming-strategy: LOWER_CAMEL_CASE
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/content_hub
    username: myuser
    password: mypassword
    # driver-class-name: org.postgresql.Driver # spring boot가 datasource.url의 값을 해석하여 알아서 설정해주기 때문에 지정해주지 않아도 된다
  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none 중 선택/ update: DB 테이블과 엔티티 매핑정보를 비교해 변경 사항만 수정,추가
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  # SQL 로그 출력
    open-in-view: false # true로 설정하면 View 렌더링 중에도 데이터베이스 쿼리가 실행될 수 있음
  data:
    redis:
      host: localhost
      port: 6379
      # 필요시 password: yourpassword
      # database: 0
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

#Server Config
server:
  servlet:
    session:
      cookie: # JSESSIONID 쿠키 설정
        http-only: true # true의 경우, javascript에서 접근 불가
        secure: false # 로컬 개발환경에선 false 가능 (https 아니면 true 쓰면 안 됨)
        same-site: lax # 운영환경에서는 strict

#Log Config
logging:
  level:
    root: INFO
    com:
      cjy:
        contenthub: INFO
  file:
    name: logs/app.log
    #org.springframework.security: DEBUG

#TMDB API Config
tmdb:
  api:
    key: ${TMDB_API_KEY}
    token: ${TMDB_API_TOKEN}
  url: 
    baseUrl: https://api.themoviedb.org
    tvSearchPath: /3/search/tv
    movieSearchPath: /3/search/movie
    multiSearchPath: /3/search/multi
    tvGenrePath: /3/genre/tv/list
    movieGenrePath: /3/genre/movie/list
    tvCreditsPath: /3/tv/%s/credits
    movieCreditsPath: /3/movie/%s/credits
    tvDetailPath: /3/tv/%s
    movieDetailPath: /3/movie/%s
    personDetailPath: /3/person/%s
    tvWatchProvidersPath: /3/tv/%s/watch/providers
    movieWatchProvidersPath: /3/movie/%s/watch/providers
    tvRecommendationsPath: /3/tv/%s/recommendations
    movieRecommendationsPath: /3/movie/%s/recommendations
    tvSimilarPath: /3/tv/%s/similar
    movieSimilarPath: /3/movie/%s/similar
  custom:
    perMainPage: 8
    autoCompleteCount: 15
    retryCount: 2
    connectionRequestTimeout: 10 # 초 단위
    responseTimeout: 15 # 초 단위
    maxConnTotal: 80
    maxConnPerRoute: 20

#Anilist API Config
anilist:
  url:
    baseUrl: https://graphql.anilist.co
  custom:
    perMainPage: 12
    perMorePage: 18
    perCharacterPage: 25
    connectionRequestTimeout: 10 # 초 단위
    responseTimeout: 15 # 초 단위
    maxConnTotal: 80
    maxConnPerRoute: 20

#DeepL API Config
deepl:
  api:
    key: ${DEEPL_API_KEY}
  url:
    baseUrl: https://api-free.deepl.com/v2
    translatePath: /translate
  custom:
    connectionRequestTimeout: 10 # 초 단위
    responseTimeout: 15 # 초 단위
    maxConnTotal: 100
    maxConnPerRoute: 30

#Login Config
login:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  naver:
    api:
      clientId: ${NAVER_CLIENT_ID}
      clientSecret: ${NAVER_CLIENT_SECRET}
    url:
      tokenIssueUrl: https://nid.naver.com/oauth2.0/token
      userInfoUrl: https://openapi.naver.com/v1/nid/me
    custom:
      refreshTokenExpiresIn: 365 # 일 단위
      connectionRequestTimeout: 5 # 초 단위
      responseTimeout: 10 # 초 단위
      maxConnTotal: 20
      maxConnPerRoute: 10
  kakao:
    api:
      clientSecret: ${KAKAO_CLIENT_SECRET}
    url:
      tokenIssueUrl: https://kauth.kakao.com/oauth/token
      oidcUserInfoUrl: https://kapi.kakao.com/v1/oidc/userinfo
      userInfoUrl: https://kapi.kakao.com/v2/user/me
      logoutUrl: https://kapi.kakao.com/v1/user/logout
    custom:
      refreshTokenExpiresIn: 60 # 일 단위
      connectionRequestTimeout: 5 # 초 단위
      responseTimeout: 10 # 초 단위
      maxConnTotal: 20
      maxConnPerRoute: 10

#Application Config
app:
  url: http://192.168.219.101:3000
  prefix: /api
  version: "" # 필요 시 "/v1"로 변경
  maintenance:
    mode: ${MAINTENANCE_MODE:false}
  webClient:
    maxInMemorySize: 10 # MB
  comment:
    perPage: 20
  myComments:
    perPage: 10
  wishlist:
    maxRegistrationSize: 500
  rate-limit:
    defaults:
      max-request-count: 60
      seconds: 60
    rules:
      # common
      - path: "/common/getCsrfToken"
        max-request-count: 20
        seconds: 60
      - path: "/common/getMediaTypes"
        max-request-count: 20
        seconds: 60
      - path: "/common/setAdultFlg"
        max-request-count: 20
        seconds: 60
      - path: "/common/clearAdultFlg"
        max-request-count: 20
        seconds: 60
      # character
      - path: "/character/getCharacter"
        max-request-count: 60
        seconds: 60
      - path: "/character/getStaff"
        max-request-count: 60
        seconds: 60
      # detail/comments
      - path: "/detail/comments/saveComment"
        max-request-count: 10
        seconds: 60
      - path: "/detail/comments/updateComment"
        max-request-count: 10
        seconds: 60
      - path: "/detail/comments/deleteComment"
        max-request-count: 10
        seconds: 60
      - path: "/detail/comments/getCommentList"
        max-request-count: 100
        seconds: 60
      - path: "/detail/comments/getStarRatingAverage"
        max-request-count: 60
        seconds: 60
      # detail/information
      - path: "/detail/information/getTvDetail"
        max-request-count: 60
        seconds: 60
      - path: "/detail/information/getMovieDetail"
        max-request-count: 60
        seconds: 60
      - path: "/detail/information/getComicsDetail"
        max-request-count: 60
        seconds: 60
      - path: "/detail/information/getComicsCharacterList"
        max-request-count: 100
        seconds: 60
      - path: "/detail/information/getComicsStaffList"
        max-request-count: 100
        seconds: 60
      # detail/recommendation
      - path: "/detail/recommendation/getTvRecommendations"
        max-request-count: 100
        seconds: 60
      - path: "/detail/recommendation/getMovieRecommendations"
        max-request-count: 100
        seconds: 60
      - path: "/detail/recommendation/getComicsRecommendations"
        max-request-count: 100
        seconds: 60
      # home
      - path: "/home/rankings"
        max-request-count: 60
        seconds: 60
      # login
      - path: "/login/getNaverLoginInfo"
        max-request-count: 10
        seconds: 60
      - path: "/login/updateNaverLoginInfo"
        max-request-count: 10
        seconds: 60
      - path: "/login/getNaverUserInfo"
        max-request-count: 10
        seconds: 60
      - path: "/login/deleteNaverToken"
        max-request-count: 10
        seconds: 60
      - path: "/login/getKakaoLoginInfo"
        max-request-count: 10
        seconds: 60
      - path: "/login/updateKakaoLoginInfo"
        max-request-count: 10
        seconds: 60
      - path: "/login/getKakaoUserInfo"
        max-request-count: 10
        seconds: 60
      - path: "/login/deleteKakaoToken"
        max-request-count: 10
        seconds: 60
      # my/comments
      - path: "/my/comments/getMyCommentList"
        max-request-count: 60
        seconds: 60
      # person
      - path: "/person/getPersonDetails"
        max-request-count: 60
        seconds: 60
      # serach
      - path: "/search/searchKeyword"
        max-request-count: 180
        seconds: 60
      - path: "/search/searchVideo"
        max-request-count: 60
        seconds: 60
      - path: "/search/searchAni"
        max-request-count: 100
        seconds: 60
      - path: "/search/searchTvExceptAni"
        max-request-count: 100
        seconds: 60
      - path: "/search/searchMovie"
        max-request-count: 100
        seconds: 60
      - path: "/search/searchComics"
        max-request-count: 100
        seconds: 60
      # wishlist
      - path: "/wishlist/saveWishlist"
        max-request-count: 100
        seconds: 60
      - path: "/wishlist/deleteWishlist"
        max-request-count: 60
        seconds: 60
      - path: "/wishlist/checkWishlist"
        max-request-count: 100
        seconds: 60
      - path: "/wishlist/getWishlist"
        max-request-count: 60
        seconds: 60

