server {
    listen 80;
    server_name content-hub.info www.content-hub.info;

    # React 정적 파일
    root /usr/share/nginx/html;
    index index.html;

    # 프론트 라우팅 해결 (SPA)
    location / {
        try_files $uri /index.html;
    }

    # 백엔드 API 프록시
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
	
	# Actuator health 프록시 (내부 관리 용도로만)
    location /_internal/health {
        proxy_pass http://backend:8081/actuator/health;
        proxy_set_header Host $host;
    }
}
