server {
    listen 80;
    server_name content-hub.info www.content-hub.info;

    # Let's Encrypt 인증 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 모든 HTTP 요청을 HTTPS로 영구 리다이렉트
    rewrite ^ https://$host$request_uri? permanent;
}

server {
    # 443 포트를 SSL로 수신
    listen 443 ssl;
    server_name content-hub.info www.content-hub.info;

    # 도메인에 'www' 붙을 시 리다이렉트(HTTP Status Code 301 영구 이동(Moved Permanently))
    if ($host = 'www.content-hub.info') {
        return 301 https://content-hub.info$request_uri;
    }

    # SSL 인증서 경로
    ssl_certificate     /etc/letsencrypt/live/content-hub.info/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/content-hub.info/privkey.pem;
	# 사용 프로토콜
	ssl_protocols       TLSv1.2 TLSv1.3;
	# 암호화 방식
    ssl_ciphers         HIGH:!aNULL:!MD5;
	# 서버(Nginx)가 선호하는 암호화 방식을 사용
	ssl_prefer_server_ciphers on;
	# "SSL" 공유 메모리 공간 할당
    ssl_session_cache   shared:SSL:10m;
	# 캐시된 SSL 세션 정보 유효 기간 설정
    ssl_session_timeout 1h;

    # 보안 헤더
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
	
	# gzip 압축
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_vary on;
    gzip_min_length 1024;

    # React 정적 파일
    root /usr/share/nginx/html;
    index index.html;
		
	# 1순위: 정적 자산(JS, CSS 등) 효율적인 캐싱 적용 (파일명 해시 활용한 캐싱)
	location /assets/ {
	    expires 1y;
        add_header Cache-Control "public, immutable"; # 파일명이 안바뀌면 계속 캐시 사용
        try_files $uri =404;
    }
	
	# 2순위: 기타 정적 파일 확장자 처리
    location ~* \.(js|css|map|json|png|jpg|jpeg|gif|svg|webp|ico)$ {
	    expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # 3순위: 백엔드 API 프록시
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4순위: Actuator health 프록시 (내부 관리 용도로만)
    location /_internal/health {
        proxy_pass http://backend:8081/actuator/health;
        proxy_set_header Host $host;
    }
	
	# 5순위: index.html 및 루트 경로: 캐싱 방지 설정 / 프론트 라우팅 해결 (SPA)
    location / {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
		
		root /usr/share/nginx/html; # 프론트엔드 빌드 결과물 경로
		index index.html;
		# 1. 파일이 있는지 확인($uri) 
		# 2. 디렉토리가 있는지 확인($uri/) 
		# 3. 없으면 index.html을 반환(프론트엔드 라우팅에 위임)
        try_files $uri $uri/ /index.html;
    }
}
