# Staging Environment

# Spring Config
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: content
    schemas: content
    validate-on-migrate: true
    baseline-on-migrate: false
  graphql:
    graphiql:
      enabled: false # 필요시 QA 편의 위해 true 설정 (보안/접근제어 전제)
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    user: 
      name: ${ACTUATOR_USER}
      password: ${ACTUATOR_PASSWORD} # DelegatingPasswordEncoder를 이용하여 {bcrypt}로 해시된 비밀번호
      roles: ACTUATOR

# Security Config
security:
  csrf:
    cookie:
      http-only: false
      secure: true
      same-site: Lax   # 프론트/백 도메인이 다르면 'None'
      domain: ${DOMAIN:}
      path: /

# Server Config
server:
  servlet:
    session:
      cookie: # JSESSIONID 쿠키 설정
        http-only: true
        secure: true
        same-site: lax  # back/front 서로 다른 도메인/서브도메인이라면 'none'
  address: 0.0.0.0
  forward-headers-strategy: framework

# Log Config
logging:
  file:
    name: /app/logs/app.log
  level:
    root: INFO
    com:
      cjy:
        contenthub: DEBUG  # QA 편의상 애플리케이션만 DEBUG
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB
      clean-history-on-start: false # 어플리케이션 시작 시 로그 파일 클리어 설정
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

# Actuator Config
management:
  server:
    port: 8081 # 스테이징에선 관리 포트 분리
    address: 0.0.0.0   # QA(품질 보증) 접근 필요 없으면 127.0.0.1 유지
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info, health, beans, conditions, metrics
  endpoint:
    health:
      show-details: when-authorized

# info
info:
  app:
    environment: staging

# Login Config
login:
  cookie:
    http-only: true
    secure: true
    same-site: Lax   # 프론트/백 도메인이 다르면 'None'
    domain: ${DOMAIN:}
    path: /

# Application Config
app:
  url: ${APP_URL} # 스테이징 프론트 Origin(https://)
  cors:
    enabled: true # 스테이징에서 프론트/백 도메인 분리 시 true
  actuator:
    developer-mode: false
