# Production Environment

# Spring Config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  graphql:
    graphiql:
      enabled: false
  security:
    user: 
      name: ${ACTUATOR_USER} # "actuator"
      password: ${ACTUATOR_PASSWORD} # DelegatingPasswordEncoder를 이용하여 {bcrypt}로 해시된 비밀번호 -> 실제로는 "actuatorPassword" 를 입력
      roles: ACTUATOR

# Security Config
security:
  csrf:
    cookie:
      http-only: false
      secure: true
      same-site: Lax
#      domain: ${DOMAIN} # 같은 호스트의 경우 생략
      path: /

# Server Config
server:
  servlet:
    session:
      cookie: # JSESSIONID 쿠키 설정
        http-only: true
        secure: true
        same-site: lax # back/front 서로 다른 도메인/서브도메인이라면 'none'
  address: 0.0.0.0
  forward-headers-strategy: framework # Proxy(리버스 프록시 뒤에서 동작)

# Log Config
logging:
  level:
    root: INFO
    com:
      cjy:
        contenthub: INFO

# Actuator Config
management:
  server:
    port: 8081 # 운영에선 관리 포트 분리
    address: 127.0.0.1 # 로컬루프백 바인딩 후 프록시에서만 접근
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info, health, beans, conditions, metrics
  endpoint:
    health:
      show-details: when-authorized

# info
info:
  app:
    environment: prod

# Login Config
login:
  cookie:
    http-only: true
    secure: true
    same-site: Lax # back/front 서로 다른 도메인/서브도메인이라면 'None'
#    domain: ${DOMAIN} # 같은 호스트의 경우 생략
    path: /

# Application Config
app:
  url: ${DOMAIN} # 프론트엔드 Origin URL, 스킴 포함(https://)
  cors:
    enabled: false # 단일 도메인의 경우 CORS 불필요
  actuator:
    developer-mode: false
