# Development Environment

# Spring Config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://db:5432/content_hub
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}  # create, update, validate, none 중 선택/ update: DB 테이블과 엔티티 매핑정보를 비교해 변경 사항만 수정,추가
    show-sql: true # SQL 로그 출력
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: content
    schemas: content
    validate-on-migrate: true   # 초기 부트스트랩 단계에서는 false
    baseline-on-migrate: false   # 기존 DB 채택이 아니므로 false
  graphql:
    graphiql:
      enabled: true
  data:
    redis:
      host: redis
      port: 6379
  security:
    user: 
      name: actuator
      password: "{noop}password" # 실제로는 password 를 입력
      roles: ACTUATOR

# Security Config
security:
  csrf:
    cookie:
      http-only: false
      secure: false
      same-site: Lax
      domain: ${DOMAIN:}
      path: /

# Server Config
server:
  servlet:
    session:
      cookie: # JSESSIONID 쿠키 설정
        http-only: true
        secure: false
        same-site: lax
#  port: 8080
  address: 0.0.0.0 # 모든 네트워크 인터페이스에서 외부 접속을 허용

# Log Config
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: DEBUG
    com:
      cjy:
        contenthub: DEBUG

# Actuator Config
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
#        include: "*" # 모든 엔드포인트를 웹에 노출
        include: info, health, beans, conditions, metrics, env
  endpoint:
    health:
      show-details: always

# info
info:
  app:
    environment: dev

# Login Config
login:
  cookie:
    http-only: true
    secure: false
    same-site: Lax
    domain: ${DOMAIN:}
    path: /

# Application Config
app:
  url: ${APP_URL} # 프론트엔드 로컬IP:PORT번호
  cors:
    enabled: true
  actuator:
    developer-mode: true
  thread-pool:
    api-task:
      core-pool-size: 8
      max-pool-size: 32
      queue-capacity: 200
    bloking-task:
      core-pool-size: 4
      max-pool-size: 16
      queue-capacity: 100
