-- PostgreSQL schema baseline for 'content' (DDL only)

-- 환경 맞춤: 소유자/접속 계정이 myuser가 맞다면 유지
CREATE SCHEMA IF NOT EXISTS content AUTHORIZATION myuser;

-- 편의: 기본 검색 경로에 content 추가(선택)
ALTER ROLE myuser SET search_path = content, public;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- TABLES
CREATE TABLE content.content (
    content_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time timestamp(6) without time zone NOT NULL,
    update_time timestamp(6) without time zone NOT NULL,
    title character varying(500) NOT NULL,
    api_id character varying(255) NOT NULL,
    content_media_type character varying(255) NOT NULL,
    display_media_type character varying(255) NOT NULL,
    thumbnail_image_url character varying(255),
    CONSTRAINT content_unique UNIQUE (content_media_type, api_id)
);

CREATE TABLE content."user" (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time timestamp(6) without time zone NOT NULL,
    update_time timestamp(6) without time zone NOT NULL,
    nickname character varying(50) NOT NULL,
    provider character varying(50) NOT NULL,
    email character varying(255),
    provider_id character varying(255) NOT NULL,
    status character varying(255),
    CONSTRAINT user_unique UNIQUE (provider, provider_id)
);

CREATE TABLE content.comment (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    star_rating numeric(2,1),
    bad bigint,
    content_id bigint NOT NULL,
    create_time timestamp(6) without time zone NOT NULL,
    good bigint,
    update_time timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    comment character varying(500) NOT NULL,
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES content."user"(user_id),
    CONSTRAINT fk_comment_content FOREIGN KEY (content_id) REFERENCES content.content(content_id)
);

CREATE TABLE content.wishlist (
    wishlist_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id bigint NOT NULL,
    create_time timestamp(6) without time zone NOT NULL,
    update_time timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT wishlist_unique UNIQUE (user_id, content_id),
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES content."user"(user_id),
    CONSTRAINT fk_wishlist_content FOREIGN KEY (content_id) REFERENCES content.content(content_id)
);

-- INDEXES
CREATE INDEX idx_api_id ON content.content USING btree (api_id);
CREATE INDEX idx_content_media_type_api_id ON content.content USING btree (content_media_type, api_id);

CREATE INDEX idx_user_id ON content.comment USING btree (user_id);
CREATE INDEX idx_content_id ON content.comment USING btree (content_id);
CREATE INDEX idx_create_time ON content.comment USING btree (create_time);
CREATE INDEX idx_star_rating ON content.comment USING btree (star_rating);

CREATE INDEX idx_wishlist_user_id ON content.wishlist USING btree (user_id);
CREATE INDEX idx_user_id_content_id ON content.wishlist USING btree (user_id, content_id);

-- 주의: flyway_schema_history는 Flyway가 관리하므로 생성하지 않습니다.