name: Frontend CI

on:
  push:
    paths:
      - "frontend/content-hub-frontend/**"
  pull_request:
    paths:
      - "frontend/content-hub-frontend/**"
  # 워크플로우를 GitHub 웹 인터페이스에서 수동으로 실행
  workflow_dispatch: 

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/content-hub-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # SonarCloud용 전체 히스토리

      # node 셋업
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/content-hub-frontend/package-lock.json

      # 의존성 파일 설치
      - name: Install dependencies
        run: npm ci

      # enlint 실행
      - name: Run ESLint
        run: npm run lint

      # 테스트 실행
      - name: Run Tests with Coverage
        run: npm run test:run -- --coverage.enabled=true --coverage.reporter=lcov
        
      # Sonar Cloud Scan
      - name: Sonar Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # 프로젝트 루트 경로 설정
          projectBaseDir: frontend/content-hub-frontend
      
      # 빌드
      - name: Build
        run: npm run build
